spring.application.name=ProductServiceJune24

#spring.autoconfigure.exclude=\
#org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
#org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

logging.level.org.springFramework.web=TRACE

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/productservicejune24
spring.datasource.username=productservicejune24user
#spring.datasource.password=secret
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true

# spring.jpa.show-sql: true -> all the queries wll be take are by Hibernate.. for every operation what query hibernate is using will be
#printed in the log file